services:
  redis:
    image: docker.io/bitnami/redis:7.0.7
    environment:
      - REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
      - ALLOW_EMPTY_PASSWORD=yes # No auth need
    volumes:
      - ./users.acl:/opt/bitnami/redis/mounted-etc/users.acl
    ports:
      - '6379:6379'
