services:
  redis:
    image: docker.io/bitnami/redis:7.0.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # No auth need
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL # disable some command
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
