services:
  redis:
    image: docker.io/bitnami/redis:7.0.2
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=password123 # auth_token authentication
    ports:
      - '6379:6379'
