name: GitHub Pacakges

on:
  workflow_dispatch:
    inputs:
      push-image:
        description: "push-image: true - build and push image. false - build only."
        required: true
        default: false
        type: boolean
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  DOCKER_PUSH_ENABLED: "${{ inputs.push-image && true || (github.event_name == 'push' || github.event_name == 'schedule') }}"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./github_packages/csharp/
            dockerfile: ./github_packages/csharp/helloworld/Dockerfile
            tag: csharp-helloworld
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/git-shortsha@main
        id: sha
      - uses: guitarrapc/actions/.github/actions/to-lower@main
        id: lower
        with:
          value: ${{ matrix.tag }}

      # docker push (auto using buildkit)
      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ env.DOCKER_PUSH_ENABLED == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}-latest-${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (tag)
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ env.DOCKER_PUSH_ENABLED == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.sha.outputs.sha-short }}-${{ matrix.tag }}
          labels: ${{ steps.meta.outputs.labels }}
